---
- name: Install Nginx
  hosts: localhost
  become: yes

  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: latest

    - name: Ensure Nginx service Running
      service:
        name: nginx
        state: started
        enabled: yes